# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capybara-page-object"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andy Waite"]
  s.date = "2012-07-24"
  s.description = "Page Objects for Capybara"
  s.email = "andy@andywaite.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "capybara-page-object.gemspec",
    "lib/capybara-page-object.rb",
    "lib/capybara-page-object/collections.rb",
    "lib/capybara-page-object/component.rb",
    "lib/capybara-page-object/delegators.rb",
    "lib/capybara-page-object/element.rb",
    "lib/capybara-page-object/elements.rb",
    "lib/capybara-page-object/elements/anchor.rb",
    "lib/capybara-page-object/elements/form.rb",
    "lib/capybara-page-object/elements/form_field.rb",
    "lib/capybara-page-object/elements/head.rb",
    "lib/capybara-page-object/elements/image.rb",
    "lib/capybara-page-object/elements/input.rb",
    "lib/capybara-page-object/elements/list.rb",
    "lib/capybara-page-object/elements/list_item.rb",
    "lib/capybara-page-object/elements/meta.rb",
    "lib/capybara-page-object/elements/select.rb",
    "lib/capybara-page-object/elements/table.rb",
    "lib/capybara-page-object/elements/table_header.rb",
    "lib/capybara-page-object/elements/table_row.rb",
    "lib/capybara-page-object/elements/text_based_input.rb",
    "lib/capybara-page-object/elements/textarea.rb",
    "lib/capybara-page-object/extensions/capybara.rb",
    "lib/capybara-page-object/extensions/enumerable.rb",
    "lib/capybara-page-object/html5_data.rb",
    "lib/capybara-page-object/key_value.rb",
    "lib/capybara-page-object/node.rb",
    "lib/capybara-page-object/page.rb",
    "spec/common_spec.rb",
    "spec/element/anchor_spec.rb",
    "spec/element/base_spec.rb",
    "spec/element/form_field_spec.rb",
    "spec/element/form_spec.rb",
    "spec/element/head_spec.rb",
    "spec/element/image_spec.rb",
    "spec/element/input_spec.rb",
    "spec/element/list_item_spec.rb",
    "spec/element/list_spec.rb",
    "spec/element/meta_spec.rb",
    "spec/element/select_spec.rb",
    "spec/element/table_row_spec.rb",
    "spec/element/table_spec.rb",
    "spec/element/textarea_spec.rb",
    "spec/fixtures/node.html",
    "spec/helper.rb",
    "spec/node_spec.rb",
    "spec/page_spec.rb"
  ]
  s.homepage = "http://github.com/andyw8/capybara-page-object"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Page Objects for Capybara"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["> 2.1.0"])
      s.add_runtime_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
    else
      s.add_dependency(%q<activesupport>, ["> 2.1.0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
    end
  else
    s.add_dependency(%q<activesupport>, ["> 2.1.0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
  end
end

