# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capybara-page-object}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Andy Waite}]
  s.date = %q{2012-04-08}
  s.description = %q{Page Objects for Capybara}
  s.email = %q{andy@andywaite.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "capybara-page-object.gemspec",
    "lib/capybara-page-object.rb",
    "lib/collections.rb",
    "lib/delegators.rb",
    "lib/element.rb",
    "lib/element/TODO.md",
    "lib/element/anchor.rb",
    "lib/element/form.rb",
    "lib/element/form_field.rb",
    "lib/element/head.rb",
    "lib/element/image.rb",
    "lib/element/input.rb",
    "lib/element/list.rb",
    "lib/element/list_item.rb",
    "lib/element/meta.rb",
    "lib/element/select.rb",
    "lib/element/table.rb",
    "lib/element/table_header.rb",
    "lib/element/table_row.rb",
    "lib/element/text_based_input.rb",
    "lib/element/textarea.rb",
    "lib/html5_data.rb",
    "lib/key_value.rb",
    "lib/node.rb",
    "lib/page.rb",
    "spec/common_spec.rb",
    "spec/element/anchor_spec.rb",
    "spec/element/base_spec.rb",
    "spec/element/form_field_spec.rb",
    "spec/element/form_spec.rb",
    "spec/element/head_spec.rb",
    "spec/element/image_spec.rb",
    "spec/element/input_spec.rb",
    "spec/element/list_item_spec.rb",
    "spec/element/list_spec.rb",
    "spec/element/meta_spec.rb",
    "spec/element/select_spec.rb",
    "spec/element/table_row_spec.rb",
    "spec/element/table_spec.rb",
    "spec/element/textarea_spec.rb",
    "spec/fixtures/node.html",
    "spec/helper.rb",
    "spec/node_spec.rb",
    "spec/page_spec.rb"
  ]
  s.homepage = %q{http://github.com/andyw8/capybara-page-object}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Page Objects for Capybara}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
    else
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
    end
  else
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
  end
end

