# -*- encoding : utf-8 -*-
require 'capybara-page-object/elements/text_based_input'
require 'capybara-page-object/elements/anchor'
require 'capybara-page-object/elements/form'
require 'capybara-page-object/elements/image'
require 'capybara-page-object/elements/form_field'
require 'capybara-page-object/elements/head'
require 'capybara-page-object/elements/input'
require 'capybara-page-object/elements/list'
require 'capybara-page-object/elements/list_item'
require 'capybara-page-object/elements/meta'
require 'capybara-page-object/elements/select'
require 'capybara-page-object/elements/table'
require 'capybara-page-object/elements/table_row'
require 'capybara-page-object/elements/table_header'
require 'capybara-page-object/elements/textarea'
